spin_manifest_version = 2

[application]
name = "advent-2024"
version = "0.1.0"
authors = ["Darwin Boersma <darwin@sadlark.com>"]
description = "Spin app for Advent of Spin 2024!"

[[trigger.http]]
route = "/..."
component = "leptos-site"

[component.leptos-site]
source = "leptos-site/target/wasm32-wasip1/release/leptos_site.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.leptos-site.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=leptos_site cargo build --lib --target wasm32-wasip1 --release --no-default-features --features ssr"
workdir = "leptos-site"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "leptos-site-pkg"

[component.leptos-site-pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "leptos-site/target/site/pkg", destination = "/" }]
