name: "CI"
on:
  push:
    branches:
      - "main"
env:
  RUST_VERSION: "1.80.1"
  SPIN_VERSION: ""
jobs:
  spin:
    runs-on: "ubuntu-latest"
    name: Build Spin App
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "${{ env.RUST_VERSION }}"
          targets: wasm32-wasip1
      - name: Install Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          plugins: 
      - name: Install cargo-leptos
        run: cargo install --locked --version 0.2.22 cargo-leptos
      - name: Build advent-2024
        run: spin build
        working-directory: .
